name: Sync Monorepo

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Add monorepo remote
        run: git remote add monorepo https://github.com/starfederation/datastar.git

      - name: Fetch monorepo
        run: git fetch monorepo

      - name: Checkout `code/php/sdk` from `monorepo/main`
        run: git checkout monorepo/main -- code/php/sdk

      - name: Remove directories
        run: |
          rm -rf ./src
          rm -rf ./tests

      - name: Move files
        run: |
          mv code/php/sdk/* ./
          mv code/php/sdk/.* ./
          rmdir code/php/sdk

      - name: Commit changes
        run: |
          git add .
          git commit -m "Sync monorepo"
          git push origin main
