name: Sync Monorepo

on:
  #schedule:
  #  - cron: '0 * * * *' # Every hour
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Add monorepo remote
        run: git remote add monorepo https://github.com/starfederation/datastar.git

      - name: Fetch monorepo
        run: git fetch monorepo

      - name: Checkout `sdk/php` from `monorepo/develop`
        run: git checkout monorepo/develop -- sdk/php

      - name: Remove directories
        run: |
          rm -rf ./src
          rm -rf ./tests

      - name: Copy files and clean up
        run: |
          rsync -av --exclude='.github/workflows' sdk/php/ ./
          rm -rf sdk/php

      - name: Sync monorepo
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "Sync monorepo"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/starfederation/datastar-php main
